### ISSUE TITLE
Symphony of the Night (USA) mismatched hashes

### ISSUE THREAD

**Issue by Arthandas** [has207/psxtract-2#15]
Duckstation shows the hashes are mismatched

<img width="694" alt="hashes" src="https://github.com/user-attachments/assets/31e408ac-bda8-4125-872b-fcc9adcddde9">

**Comment by Arthandas** [comment]
I am worried, because any mismatches can create issues with romhacks.

**Comment by mokMan23** [comment]
> I am worried, because any mismatches can create issues with romhacks.

ROM Hacks would only modify the Data track, which is almost always clean, it shouldn't matter since the ECC's empty anyway, again, as mentioned in #3. If you're _that_ worried about it, you might as well replace the Audio tracks with known Redump versions, and patch the Data track, since you've already paid for the game.

**Comment by Arthandas** [comment]
> If you're _that_ worried about it, you might as well replace the Audio tracks with known Redump versions, and patch the Data track, since you've already paid for the game.

Going by that logic I may as well just download roms instead of dumping them myself :)

> ROM Hacks would only modify the Data track, which is almost always clean, it shouldn't matter since the ECC's empty anyway, again, as mentioned in #3.

All right, if the issue is purely cosmetic, just close this ticket I guess.

**Comment by has207** [comment]
It's not possible to retrieve original audio tracks, the at3 compression in the eboot is lossy, so yes if you want to get them to match you have to get them from an original disc or some other way.
